### ISSUE TITLE
Doesn't work for .eu domains

### ISSUE THREAD

**Issue by julox** [Domain-Connect/domainconnect_python#7]
I am triying with this command but does not work:

sudo domain-connect-dyndns setup --domain aaa.bbb.eu

The result is:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/domainconnect/domainconnect.py", line 203, in _identify_domain_connect_api
    dns = self._resolver.query('_domainconnect.{}'.format(domain_root), 'TXT')
  File "/usr/local/lib/python3.7/dist-packages/dns/resolver.py", line 1091, in query
    True)
  File "/usr/local/lib/python3.7/dist-packages/dns/resolver.py", line 1030, in resolve
    (request, answer) = resolution.next_request()
  File "/usr/local/lib/python3.7/dist-packages/dns/resolver.py", line 585, in next_request
    responses=self.nxdomain_responses)
dns.resolver.NXDOMAIN: None of DNS query names exist: _domainconnect.bbb.eu., _domainconnect.bbb.eu.8.8.8.8.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dyndns/domain_setup.py", line 16, in main
    config = dc.get_domain_config(domain)
  File "/usr/local/lib/python3.7/dist-packages/domainconnect/domainconnect.py", line 243, in get_domain_config
    domain_connect_api = self._identify_domain_connect_api(domain_root)
  File "/usr/local/lib/python3.7/dist-packages/domainconnect/domainconnect.py", line 213, in _identify_domain_connect_api
    raise NoDomainConnectRecordException('Failed to resolve "{}"'.format(domain_root))
domainconnect.domainconnect.NoDomainConnectRecordException: Failed to resolve "bbb.eu"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/domain-connect-dyndns", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/dyndns/command_line.py", line 76, in main
    print(domain_setup.main(domain, protocols, settings))
  File "/usr/local/lib/python3.7/dist-packages/dyndns/domain_setup.py", line 17, in main
    except NoDomainConnectRecordException or NoDomainConnectSettingsException:
NameError: name 'NoDomainConnectRecordException' is not defined

thanks for all

greetings

**Comment by pawel-kow** [comment]
Hi,

The issue here is that the domain bbb.eu does not exist.
It is working for any TLD as long as there is a valid TXT _domainconnect record and the DNS provider supports Domain Connect.
